import type { Metadata } from "next";
import Link from "next/link";
import { JsonLd } from "@/components/seo/JsonLd";
import { brandedTitle, siteUrl } from "@/lib/site";

export const metadata: Metadata = { title: { absolute: brandedTitle("Développeur SaaS à Nador | Laravel & React") }, description: "Développeur SaaS à Nador : Laravel, React, Next.js, API, dashboards, authentification et déploiement pour MVP et applications métier.", alternates: { canonical: "/services/developpement-saas-nador" } };

const points = ["MVP SaaS centré sur un workflow métier clair", "Authentification, utilisateurs, rôles et espaces d’administration", "API Laravel, base MySQL et interfaces React/Next.js", "Tableaux de bord, formulaires, données et déploiement", "Une proposition chiffrée après cadrage des modules et intégrations"];

export default function SaasNadorPage() { return <main className="min-h-screen bg-slate-50 px-4 py-16 text-slate-950 dark:bg-slate-950 dark:text-white"><JsonLd data={{"@context":"https://schema.org","@type":"Service",name:"Développement SaaS à Nador",provider:{"@type":"Person",name:"Youssef Youyou",url:siteUrl},areaServed:"Nador, Morocco",url:`${siteUrl}/services/developpement-saas-nador`}}/><article className="mx-auto max-w-4xl"><p className="text-sm font-black uppercase tracking-[.2em] text-violet-600">Nador · Maroc · Remote</p><h1 className="mt-4 text-4xl font-black tracking-tight md:text-6xl">Développeur SaaS à Nador</h1><p className="mt-6 max-w-3xl text-lg leading-8 text-slate-600 dark:text-slate-300">Je conçois des applications SaaS et outils métier avec Laravel, React et Next.js : un MVP utile, une base de données claire, des rôles, un dashboard et une architecture qui peut évoluer sans prétendre livrer un produit d’entreprise complet en une seule étape.</p><section className="mt-10 grid gap-5 md:grid-cols-2">{points.map(point=><div key={point} className="rounded-3xl border border-violet-200 bg-white p-5 text-sm leading-7 shadow-sm dark:border-white/10 dark:bg-white/[.04]">{point}</div>)}</section><section className="mt-12 rounded-[2rem] border border-violet-200 bg-white p-8 dark:border-white/10 dark:bg-white/[.04]"><h2 className="text-3xl font-black">Preuve technique, pas promesse vague</h2><p className="mt-4 leading-8 text-slate-600 dark:text-slate-300">ERPlus montre une architecture Laravel API et React/Vite autour de modules RH, inventaire, finance et collaboration. Youssef Control montre une autre dimension : opérations, permissions, journalisation et interfaces sensibles conçues avec des limites de sécurité explicites.</p><div className="mt-6 flex flex-wrap gap-3"><Link className="rounded-full bg-violet-600 px-5 py-3 font-bold text-white" href="/projects/erplus">Voir ERPlus</Link><Link className="rounded-full border border-violet-300 px-5 py-3 font-bold" href="/projects/youssef-control">Voir Youssef Control</Link></div></section><section className="mt-12"><h2 className="text-3xl font-black">Questions fréquentes</h2><div className="mt-6 grid gap-4"><p><strong>Quel budget pour un SaaS ?</strong><br/>Un MVP SaaS commence à partir de 15 000 DH ; le prix final dépend des modules, rôles, intégrations et niveau de finition.</p><p><strong>Travaillez-vous avec des entreprises hors de Nador ?</strong><br/>Oui. Je suis basé à Nador et disponible pour des projets au Maroc et à distance.</p><p><strong>Peut-on commencer petit ?</strong><br/>Oui. Le bon point de départ est un workflow principal, puis des modules ajoutés après validation.</p></div></section><Link href="/contact" className="mt-12 inline-flex rounded-full bg-violet-600 px-6 py-3 font-bold text-white">Discuter de votre SaaS</Link></article></main>; }
