export const profile = {
  name: "Youssef Youyou",
  title: "Junior Full-Stack Web Developer",
  heroPromise:
    "I turn business workflows into Laravel + React systems: dashboards, APIs, portals, SEO-ready platforms and deployment-ready products.",
  positioning:
    "Laravel Backend Developer | React/Next.js Frontend Developer | API Integration | Admin Dashboards | SaaS | B2B/B2C Web Platforms | Deployment & SEO",
  location: "Nador, Morocco",
  availability:
    "Available for freelance, remote, Marrakech & Morocco opportunities",
  description:
    "I build modern Laravel, React/Next.js, API-driven, SEO-ready and production-deployed web platforms for businesses, startups, and digital projects.",
  email: "contact@youssefyouyou.com",
  website: "https://youssefyouyou.com",
  github: "https://github.com/youssefyouyoudev",
  linkedin: "https://linkedin.com/in/youssefyouyoudev",
};

export const stackBadges = ["Laravel", "React", "Next.js", "MySQL", "APIs", "Nginx", "SEO"];

export const proofPoints = [
  "Freelance web, SaaS and microservices projects from 2019-2023",
  "Remote React.js work with MediaTechly London in 2023",
  "Current administrative role at Vectalia Nador with digitalization and IT support experience",
  "Strong fit for dashboards, APIs, portals, internal tools and deployment support",
];

export const stats = [
  { value: "4+", label: "Years project experience", detail: "Freelance web, SaaS and microservices from 2019-2023.", tone: "Production practice" },
  { value: "10+", label: "Practical project types", detail: "Websites, dashboards, SaaS, e-commerce, portals, admin tools, archiving, automation, APIs and support.", tone: "Broad delivery" },
  { value: "6", label: "Technical areas", detail: "Backend, Frontend, Database, DevOps, Security, IT/Admin.", tone: "Full-stack coverage" },
  { value: "4", label: "Languages", detail: "Arabic, French, English and German B1.", tone: "Client communication" },
];

export const skillDistribution = [
  { name: "Backend", value: 90 },
  { name: "Frontend", value: 88 },
  { name: "Database", value: 82 },
  { name: "DevOps", value: 75 },
  { name: "Security", value: 70 },
  { name: "IT/Digitalization", value: 85 },
  { name: "UI/Design", value: 72 },
];

export const timeline = [
  { year: "2019", event: "Freelance web development started" },
  { year: "2021", event: "Full-stack web development foundations" },
  { year: "2023", event: "MediaTechly React remote experience" },
  { year: "2023", event: "Administrative digitalization and IT support" },
  { year: "2026", event: "Full-stack portfolio and production systems focus" },
];

export const services = [
  ["Business websites", "Premium SEO-ready websites for service businesses, agencies and local brands.", "B2B/B2C"],
  ["SaaS platforms", "Multi-user product foundations with dashboards, role structure and analytics-ready modules.", "B2B"],
  ["Admin dashboards", "Operational dashboards for content, users, reports, workflows and internal data.", "B2B"],
  ["E-commerce websites", "Catalogues, carts, orders, client areas, payment structure and reporting.", "B2C/B2B"],
  ["Client portals", "Secure spaces for customers, documents, project statuses and communication.", "B2B/B2C"],
  ["Internal management systems", "Practical tools that reduce manual work and help teams operate faster.", "B2B"],
  ["API integrations", "REST integrations connecting Laravel, React, third-party services and automation flows.", "B2B/B2C"],
  ["Laravel backend development", "Validation, Resources, Policies, Sanctum auth, migrations and clean API contracts.", "B2B/B2C"],
  ["React/Next.js frontend development", "Fast responsive interfaces with accessible components and polished UI states.", "B2B/B2C"],
  ["Database design", "Relational schemas for dashboards, SaaS modules, portals and content systems.", "B2B"],
  ["SEO technical optimization", "Metadata, JSON-LD, sitemaps, semantic HTML, performance and clean slugs.", "B2B/B2C"],
  ["Deployment on Ubuntu/Nginx", "Nginx, PHP-FPM, MySQL, SSL, PM2, env setup and cache optimization.", "B2B"],
  ["IT support and process digitalization", "Helping teams replace repetitive manual work with practical digital workflows.", "B2B"],
  ["Excel/VBA automation", "Forms, calculations, filters, reports and tracking tables for productivity.", "B2B"],
  ["Digital archiving systems", "Searchable document organization, tracking and simple admin-facing interfaces.", "B2B"],
].map(([title, description, tag]) => ({ title, description, tag, slug: title.toLowerCase().replaceAll("/", "").replaceAll(" ", "-") }));

export const skills = {
  "Main stack": ["Laravel", "PHP", "React.js", "Next.js", "Vue.js", "MySQL", "REST APIs", "Tailwind CSS"],
  "Production tools": ["Linux", "Nginx", "Git", "Cloudflare", "Postman", "Production deployment"],
  "Business systems": ["Admin dashboards", "Client portals", "Roles and permissions", "Reporting interfaces", "Relational database design"],
  "Automation support": ["Excel Advanced", "VBA", "Digital archiving", "Workflow automation", "SEO basics", "OWASP basics"],
};

export const projects = [
  {
    title: "RiFiTV",
    slug: "rifitv",
    category: "Media platform / football content / streaming-style interface",
    subtitle: "Media Platform - Laravel - Blade - Vite - Nginx",
    shortDescription: "A media-style web platform focused on live TV-style navigation, football content, channel organization and user-friendly access across devices.",
    caseStudyUrl: "/projects/rifitv",
    image: "/images/projects/rifitv-showcase.png",
    imageAlt: "RiFiTV media platform project preview",
    seoTitle: "RiFiTV Case Study | Youssef Youyou Portfolio",
    seoDescription: "Case study for RiFiTV, a Laravel media-style platform focused on content organization, responsive UI, SEO structure and production deployment.",
    stack: ["Laravel", "Blade", "Vite", "JavaScript", "MySQL", "Nginx", "Cloudflare"],
    features: ["Channel and category organization", "Live TV-style interface", "Football/match content structure", "Search and navigation", "Responsive design", "SEO-oriented content sections", "Production deployment experience"],
    businessValue: "Improves user access to media content, creates a more organized viewing experience and supports monetization/SEO structure.",
    problems: ["Improving user navigation", "Organizing media/channel content", "Handling production cache/build issues", "Improving mobile and TV usability", "Optimizing SEO structure without overpromising"],
    businessProblem: "Users need a simple, fast and organized way to browse channels, matches and media content without a confusing interface.",
    solution: "A Laravel-based platform with a responsive UI, categorized content, search, channel/match presentation, SEO-friendly structure and production deployment.",
    myRole: "Full-stack development, UI/UX improvement, Laravel/Blade/Vite implementation, deployment support and production troubleshooting.",
    targetUsers: "Football/media visitors, content platform owners and users browsing across desktop, mobile and TV-style screens.",
    deliverables: ["Laravel content structure", "Mobile-first player interface", "SEO category layout", "Ad placement structure", "Nginx/Cloudflare deployment support"],
    architecture: "Laravel Blade application with Vite assets, channel/content management, SEO-friendly routes, cache-aware production build and Nginx/Cloudflare delivery.",
    impact: "Improved platform usability, content discoverability, monetization readiness and production reliability without overstating traffic or revenue.",
    recruiterSignal: "Shows practical Laravel production work, deployment troubleshooting, SEO thinking and user-experience decisions for a real content platform.",
    learned: "Better understanding of media UI, deployment workflow, production caching, Cloudflare/Nginx behavior and user-first navigation.",
  },
  {
    title: "ERPlus",
    slug: "erplus",
    category: "Business management platform / SaaS / HR / inventory",
    subtitle: "Business Management Platform - Laravel - React - MySQL",
    shortDescription: "A business management platform concept focused on HR workflows, payroll-style features, inventory modules, dashboards and admin control.",
    caseStudyUrl: "/projects/erplus",
    image: "/images/projects/erplus-showcase.png",
    imageAlt: "ERPlus business management dashboard project preview",
    seoTitle: "ERPlus Case Study | Youssef Youyou Portfolio",
    seoDescription: "Case study for ERPlus, a Laravel and React business management platform concept for HR workflows, inventory modules, admin dashboards and API-driven structure.",
    stack: ["Laravel", "React", "Vite", "MySQL", "Tailwind CSS", "REST API", "Nginx"],
    features: ["HR module", "Payroll/payslip workflows", "Inventory module", "Admin dashboard", "Authentication", "API-driven frontend", "Reporting interface", "Landing pages"],
    businessValue: "Helps businesses organize internal operations through dashboards, structured workflows and centralized admin control.",
    problems: ["Backend/frontend separation", "API structure", "Asset and build path issues", "HR workflow organization", "Nginx and deployment configuration"],
    businessProblem: "Businesses need one organized system to manage people, processes, HR data, inventory information and operational dashboards.",
    solution: "A Laravel backend and React frontend structure with API-driven modules, admin dashboards, authentication, HR workflows and inventory management.",
    myRole: "Backend/frontend structure, API integration, UI improvements, deployment support, dashboard logic and production issue fixing.",
    targetUsers: "Small business teams, HR/admin users and managers who need clearer operational dashboards.",
    deliverables: ["Laravel API foundation", "React Vite frontend", "Authentication flow", "HR and inventory modules", "Admin dashboard", "Deployment configuration"],
    architecture: "Separated Laravel backend and React frontend, MySQL relational data, protected business modules, reusable dashboard views and Nginx production routing.",
    impact: "Created a clearer SaaS-style foundation for internal workflows, user management and future feature growth.",
    recruiterSignal: "Shows backend/frontend separation, API contracts, authentication, dashboard UX and deployment awareness.",
    learned: "Improved experience with Laravel APIs, React dashboards, SaaS structure, deployment issues and business workflow design.",
  },
  {
    title: "Digital Archiving System",
    slug: "digital-archiving-system",
    category: "Internal tool / document management / digitalization",
    subtitle: "Internal Tool - Vue.js - Document Tracking - Automation",
    shortDescription: "An internal digital archiving concept for organizing, searching, tracking and managing administrative documents more efficiently.",
    caseStudyUrl: "/projects/digital-archiving-system",
    image: "/images/projects/digital-archiving-showcase.png",
    imageAlt: "Digital Archiving System document management project preview",
    seoTitle: "Digital Archiving System Case Study | Youssef Youyou Portfolio",
    seoDescription: "Case study for a digital archiving system focused on document organization, search, tracking and internal administrative workflow improvement.",
    stack: ["Vue.js", "JavaScript", "Excel/VBA logic", "MySQL concept", "Digital workflow"],
    features: ["Document organization", "Search and filtering", "Status tracking", "Folder/category structure", "Upload/scan concept", "Activity tracking", "Workflow support"],
    businessValue: "Helps teams find documents faster, reduce repetitive administrative work and improve organization.",
    problems: ["Reducing manual search time", "Making document tracking clearer", "Improving administrative workflow", "Structuring files and metadata", "Supporting internal digital transformation"],
    businessProblem: "Manual document handling creates slow search, poor tracking, duplicate work and difficulty following administrative records.",
    solution: "A structured digital archiving interface with document categories, metadata, search, tracking status, workflow support and activity overview.",
    myRole: "Process analysis, UI concept, simple interface development, digitalization support and workflow improvement.",
    targetUsers: "Administrative teams, document managers and internal staff handling recurring files and records.",
    deliverables: ["Document organization logic", "Search interface concept", "Tracking workflow", "Vue.js access UI", "Excel/VBA automation support"],
    architecture: "Simple web interfaces supported by structured data logic and spreadsheet automation where that remains the fastest practical tool.",
    impact: "Supported faster document access, clearer administrative tracking and less repetitive manual work.",
    recruiterSignal: "Shows business-process empathy, IT support context, Vue.js interface work and pragmatic automation thinking.",
    learned: "How to translate real administrative workflow problems into digital tools and simple interfaces.",
  },
  {
    title: "Social Media Management SaaS",
    slug: "social-media-management-saas",
    category: "SaaS / marketing platform / dashboard",
    subtitle: "SaaS Platform - Laravel - React - Analytics",
    shortDescription: "A SaaS platform concept for planning posts, managing multiple accounts, tracking engagement and organizing marketing workflows.",
    caseStudyUrl: "/projects/social-media-management-saas",
    image: "/images/projects/social-media-saas-showcase.png",
    imageAlt: "Social Media Management SaaS dashboard project preview",
    seoTitle: "Social Media Management SaaS Case Study | Youssef Youyou Portfolio",
    seoDescription: "Case study for a Laravel and React social media management SaaS concept with scheduling, analytics widgets, account management and team workflow.",
    stack: ["Laravel", "React", "MySQL", "Tailwind CSS", "Redis concept", "API"],
    features: ["Content calendar", "Scheduled posts", "Account management", "Campaign cards", "Analytics dashboard", "Team workflow", "Responsive interface"],
    businessValue: "Supports content planning, campaign visibility and better marketing workflow organization.",
    problems: ["Designing clean dashboard structure", "Organizing multi-account workflow", "Presenting analytics clearly", "Planning SaaS-style modules", "Creating reusable UI patterns"],
    businessProblem: "Small teams need a shared place to plan content, schedule posts and review simple performance signals.",
    solution: "A Laravel and React-based SaaS dashboard concept with calendar planning, scheduled posts, analytics widgets, account management and team workflow.",
    myRole: "Full-stack concept, dashboard design, Laravel/React structure, responsive UI and SaaS workflow planning.",
    targetUsers: "Marketing teams, agencies, content managers and small businesses managing recurring campaigns.",
    deliverables: ["Multi-user SaaS structure", "Scheduling module concept", "Analytics dashboard", "Responsive React UI", "Laravel data model"],
    architecture: "Laravel and MySQL backend with account/workspace style entities, React dashboard UI and a structure ready for integrations.",
    impact: "Turned a marketing workflow into a clearer SaaS concept with room for automation, analytics and team roles.",
    recruiterSignal: "Shows SaaS thinking, multi-user modeling, dashboard planning and product workflow design.",
    learned: "Improved dashboard design, SaaS module planning and analytics UI structure.",
  },
  {
    title: "E-commerce / Client Portal Systems",
    slug: "ecommerce-client-portal",
    category: "E-commerce / client portals / business web apps",
    subtitle: "Web Applications - Laravel - MySQL - Payments",
    shortDescription: "A web application concept for product catalogs, carts, orders, client dashboards, payment workflows and admin reporting.",
    caseStudyUrl: "/projects/ecommerce-client-portal",
    image: "/images/projects/ecommerce-client-portal-showcase.png",
    imageAlt: "E-commerce client portal system project preview",
    seoTitle: "E-commerce Client Portal Systems Case Study | Youssef Youyou Portfolio",
    seoDescription: "Case study for e-commerce and client portal systems focused on product catalogs, order flows, client dashboards, admin reporting and Laravel logic.",
    stack: ["Laravel", "Blade", "Vite", "MySQL", "Tailwind CSS", "Payment workflow concept"],
    features: ["Product catalog", "Cart and order management", "Client dashboard", "Order tracking", "Payment method structure", "Admin overview", "Reporting and analytics"],
    businessValue: "Helps businesses sell online, manage customer orders and provide clients with a clear portal experience.",
    problems: ["Organizing client/admin flows", "Structuring orders and products", "Designing clean checkout logic", "Creating dashboard/reporting views", "Improving user-friendly navigation"],
    businessProblem: "Businesses need online sales systems that are easy for customers to use and easy for admins to manage.",
    solution: "A Laravel-based e-commerce/client portal structure with product listings, cart/order flow, client area, admin dashboard and reporting widgets.",
    myRole: "Full-stack development concept, database structure, Laravel logic, UI planning, admin/client workflow design.",
    targetUsers: "Business owners, online customers, admin teams and clients who need a self-service portal.",
    deliverables: ["Catalogue and cart flow", "Order management", "Client area", "Role and permission structure", "Reporting dashboard"],
    architecture: "Laravel/PHP and MySQL commerce modules with admin controls, customer-facing pages and reporting-friendly data structure.",
    impact: "Reduced manual sales handling and made client/order operations easier to manage from one system.",
    recruiterSignal: "Shows e-commerce basics, RBAC awareness, relational modeling and admin dashboard delivery.",
    learned: "Better understanding of commerce flows, admin tools, customer portals and conversion-focused UI.",
  },
  {
    title: "Excel/VBA Automation Tools",
    slug: "excel-vba-automation-tools",
    category: "Automation / reporting / productivity",
    subtitle: "Automation - Reporting - Productivity - VBA",
    shortDescription: "A set of Excel/VBA automation concepts for reports, dashboards, forms, filters, calculations and repetitive workflow reduction.",
    caseStudyUrl: "/projects/excel-vba-automation-tools",
    image: "/images/projects/excel-vba-automation-showcase.png",
    imageAlt: "Excel VBA automation dashboard project preview",
    seoTitle: "Excel/VBA Automation Tools Case Study | Youssef Youyou Portfolio",
    seoDescription: "Case study for Excel and VBA automation tools focused on reports, forms, filters, calculations and administrative productivity workflows.",
    stack: ["Excel", "VBA", "Power Query", "Power Pivot", "Charts", "Automation logic"],
    features: ["Smart forms", "Automated calculations", "Dynamic reports", "Filters", "Tracking tables", "Dashboard charts", "Workflow automation", "Export/report tools"],
    businessValue: "Saves time, reduces manual errors and improves productivity for administrative workflows.",
    problems: ["Reducing repetitive tasks", "Improving report consistency", "Making data easier to filter", "Simplifying administrative tracking", "Improving accuracy and time management"],
    businessProblem: "Teams often need immediate automation before a full web app is justified, especially around reports, forms and recurring calculations.",
    solution: "Excel/VBA automation tools with forms, dynamic reports, dashboards, filters, tracked tables and workflow automation.",
    myRole: "Excel/VBA automation, workflow analysis, reporting logic, form creation and administrative productivity improvement.",
    targetUsers: "Administrative teams, operations users and staff working with recurring reports or spreadsheet-heavy workflows.",
    deliverables: ["Excel forms", "VBA calculations", "Filtering tools", "Report tables", "Tracking workflows"],
    architecture: "Advanced Excel and VBA business logic organized around repeatable inputs, controlled calculations and report-ready outputs.",
    impact: "Cut repetitive admin effort and created a bridge from spreadsheet work to future web applications.",
    recruiterSignal: "Shows practical automation, user support, workflow analysis and the ability to solve business problems with the right tool.",
    learned: "How automation can create quick business value even without a full web app.",
  },
];

export const experiences = [
  {
    role: "Agent Administrative",
    company: "Vectalia Nador",
    date: "September 2023 - Present",
    location: "Nador, Morocco",
    points: [
      "Participated in administrative digitalization through internal IT tools.",
      "Improved digital archiving systems for organizing, searching and tracking documents.",
      "Created simple Vue.js interfaces to improve data access.",
      "Automated repetitive tasks with Excel Advanced and VBA.",
      "Provided first-level IT support and helped interns with tools, workflows and good practices.",
    ],
  },
  {
    role: "Web Developer",
    company: "MediaTechly - London, UK",
    date: "July 2023 - September 2023",
    location: "100% remote",
    points: [
      "Developed modern React.js interfaces.",
      "Improved frontend maintainability with component-based architecture.",
      "Optimized performance with lazy loading and code splitting.",
      "Improved responsive design and accessibility.",
    ],
  },
  {
    role: "Freelance Web Developer - Web, SaaS & Microservices",
    date: "June 2019 - June 2023",
    location: "Nador, Morocco / Remote",
    points: [
      "Built websites, management applications, admin dashboards and client portals.",
      "Created Laravel, PHP, React.js, JavaScript, MySQL and REST API solutions.",
      "Built authentication, notifications, user management, roles and permissions.",
      "Created e-commerce and early SaaS features with multi-user management and dashboards.",
    ],
  },
];

export const blogPosts = [
  {
    title: "How I build Laravel and React dashboards",
    slug: "how-i-build-laravel-and-react-dashboards",
    category: "Dashboards",
    excerpt: "A practical look at how I structure dashboards with Laravel APIs, React components, filters, validation and reusable UI patterns.",
    points: [
      "Define the business entities before designing screens.",
      "Use Laravel validation and API Resources to keep responses predictable.",
      "Build React components around repeated dashboard patterns: tables, filters, status badges and forms.",
      "Keep deployment and SEO details in mind when dashboards connect to public pages.",
    ],
  },
  {
    title: "From Excel automation to web applications",
    slug: "from-excel-automation-to-web-applications",
    category: "Automation",
    excerpt: "How repetitive spreadsheet workflows can become cleaner tools, dashboards or internal web applications.",
    points: [
      "Start by removing repetitive calculations and manual filtering.",
      "Identify which spreadsheet fields should become database tables.",
      "Move shared workflows into simple forms, dashboards and reports.",
      "Keep Excel when it is still the fastest useful tool, and move to web when collaboration matters.",
    ],
  },
  {
    title: "Practical API structure for admin dashboards",
    slug: "practical-api-structure-for-admin-dashboards",
    category: "APIs",
    excerpt: "Notes on organizing REST endpoints, resources, validation and frontend consumption for dashboard-style applications.",
    points: [
      "Separate public content endpoints from admin-protected workflows.",
      "Use Form Requests for validation and Resources for response shape.",
      "Track important actions such as contact messages and CV downloads.",
      "Design endpoints around UI needs without coupling everything to one screen.",
    ],
  },
  {
    title: "Why small businesses need internal dashboards",
    slug: "why-small-businesses-need-internal-dashboards",
    category: "Business systems",
    excerpt: "A simple explanation of how dashboards help teams track work, reduce manual tasks and make better decisions.",
    points: [
      "Dashboards make daily work visible: orders, documents, users, tasks or inventory.",
      "Roles and permissions keep information organized for different team members.",
      "Reports help owners understand operations without waiting for manual summaries.",
      "The best dashboard starts small and grows from real team habits.",
    ],
  },
  {
    title: "Deploying Laravel and Next.js on Ubuntu",
    slug: "deploying-laravel-and-nextjs-on-ubuntu",
    category: "Deployment",
    excerpt: "A practical deployment checklist covering Nginx, PM2, Laravel cache, environment files and production builds.",
    points: [
      "Separate the Laravel API and Next.js frontend into clear production directories.",
      "Use Nginx server blocks for the frontend domain and API subdomain.",
      "Prepare Laravel cache, queues, permissions and environment variables before launch.",
      "Run production builds carefully and keep rollback steps simple.",
    ],
  },
];
